<a href="https://colab.research.google.com/github/Vignesh424/Penguin-Species/blob/main/PenguinApp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-learn==1.2.0

In [2]:
#Import Packages
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [3]:
#Read the dataset
data = sns.load_dataset('penguins')
data

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [4]:
#Shape
data.shape

(344, 7)

In [5]:
#info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [6]:
#data fill
data.fillna(method='ffill', inplace=True)

<ipython-input-6-e508170d368e>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)


In [7]:
#Describe
data.describe()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count       344.00000     344.000000         344.000000   344.000000
mean         43.92093      17.143605         200.936047  4201.090116
std           5.45003       1.978342          14.042064   802.213531
min          32.10000      13.100000         172.000000  2700.000000
25%          39.27500      15.575000         190.000000  3550.000000
50%          44.45000      17.300000         197.000000  4050.000000
75%          48.50000      18.700000         213.250000  4756.250000
max          59.60000      21.500000         231.000000  6300.000000

In [8]:
#Features and the Target
X = data.drop(columns=['species', 'sex','island'], axis=1)
Y = data['species']

In [9]:
#Split into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=2)

In [10]:
#Algorithm
model = RandomForestClassifier()
model.fit(X_train, Y_train)

RandomForestClassifier()

In [11]:
#Predict the Value
Y_Pred = model.predict(X_test)

In [12]:
#confusion Matrix
print(metrics.confusion_matrix(Y_test, Y_Pred))

[[34  0  0]
 [ 3 18  0]
 [ 0  0 31]]


In [13]:
#Present the findings using metrics of regression
print("Accuracy:", metrics.accuracy_score(Y_test, Y_Pred))
print("Precision:", metrics.precision_score(Y_test, Y_Pred, average="macro"))
print("Recall:", metrics.recall_score(Y_test, Y_Pred, average="macro"))
print("F1 Score:", metrics.f1_score(Y_test, Y_Pred, average="macro"))

Accuracy: 0.9651162790697675
Precision: 0.9729729729729729
Recall: 0.9523809523809524
F1 Score: 0.9602744673167208


In [14]:
#Generate a Pickle file
import pickle
check= open('penguins2.pkl', 'wb')
pickle.dump(model, check)